version: "3"
services:
  db:
    container_name: "db"
    image: postgres:10.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    expose:
      - 5432
  neo-nodes:
    container_name: "neo-nodes"
    image: cityofzion/neo-privatenet
    ports:
      - "20333"
      - "20334"
      - "20335"
      - "20336"
      - "30333"
      - "30334"
      - "30335"
      - "30336"
  neo-scan:
    build: ./neo-scan
    container_name: "neo-scan2"
    depends_on:
      - db
      - neo-nodes
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_HOSTNAME: db
    links:
      - db
      - neo-nodes:20333
      - neo-nodes:20334
      - neo-nodes:20335
      - neo-nodes:20336
      - neo-nodes:30333
      - neo-nodes:30334
      - neo-nodes:30335
      - neo-nodes:30336
    ports:
      - 4001:4000   
